name: Testing on Windows
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.7
  build:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - ruby: head
        os:
          - windows-latest
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Replace libcurl.dll
      run: |
        # The `libcurl.dll` bundled with Ruby on Windows (MSYS2) has missing dependencies and cannot be loaded by `ethon` out of the box. (Ref: https://github.com/typhoeus/typhoeus/issues/720)
        choco install curl --no-progress

        $curlTools = "C:\ProgramData\chocolatey\lib\curl\tools"
        $srcDll = Get-ChildItem -Path $curlTools -Filter "libcurl*.dll" -Recurse | Select-Object -First 1

        $rubyBin = Split-Path (Get-Command ruby.exe).Source
        $destDll = Join-Path $rubyBin "libcurl.dll"
        Copy-Item -Path $srcDll.FullName -Destination $destDll -Force

    - name: unit testing
      env:
        CI: true
      run: |
        bundle exec rake test
